scene.setBackgroundImage(img`
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    cdddddccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccccccccccccccdddddccccccdddddccccccccccccccccccccccccccccccccccccccccccdddddcccccccccc
    `)
let picnicFood = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
picnicFood.setImage(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
